//        NAME   NUMBER  ARGS     CODE
DEF_CMD_ (EXIT,    0,      0,     printf ("END"))
DEF_CMD_ (PUSH,    1,      1,     Push  (CPU, Programm) )
DEF_CMD_ (PUSHR,   2,      1,     Pushr (CPU, Programm) )
DEF_CMD_ (POP,     3,      1,     Pop   (CPU, Programm) )
DEF_CMD_ (ADD,     4,      0,     Add   (&(CPU->CPU_Stack)) )
DEF_CMD_ (SUB,     5,      0,     Sub   (&(CPU->CPU_Stack)) )
DEF_CMD_ (MULT,    6,      0,     Mult  (&(CPU->CPU_Stack)) )
DEF_CMD_ (DIV,     7,      0,     Div   (&(CPU->CPU_Stack)) )
DEF_CMD_ (MOD,     8,      0,     Mod   (&(CPU->CPU_Stack)) )
DEF_CMD_ (OUT,     9,      1,     OUT   (CPU, Programm) )
DEF_CMD_ (IN,      10,     1,     IN    (CPU, Programm) )
DEF_CMD_ (JMP,     11,     1,     JMP   (CPU, Programm) )
DEF_CMD_ (JA,      12,     1,     JA    (CPU, Programm) )
DEF_CMD_ (JAE,     13,     1,     JAE   (CPU, Programm) )
DEF_CMD_ (JB,      14,     1,     JB    (CPU, Programm) )
DEF_CMD_ (JBE,     15,     1,     JBE   (CPU, Programm) )
DEF_CMD_ (JE,      16,     1,     JE    (CPU, Programm) )
DEF_CMD_ (JNE,     17,     1,     JNE   (CPU, Programm) )
DEF_CMD_ (CALL,    18,     1,     Call  (CPU, Programm) )
DEF_CMD_ (RET,     19,     0,     Ret   (CPU) )
DEF_CMD_ (SQRT,    20,     0,     SQRT  (&(CPU->CPU_Stack)) )

