DEF_ERROR (NOERROR,     0, "No errors.")
DEF_ERROR (ERRNULL,     1, "Lost a pointer to the structure.")
DEF_ERROR (ERRDATA,     2, "Lost a pointer to the Array of the structure.")
DEF_ERROR (ERRSIZE,     3, "Wrong max size of array.")
DEF_ERROR (ERRCOUNT,    4, "Wrong counter.")
DEF_ERROR (ERREMPTY,    5, "Array is empty.")
DEF_ERROR (ERRFULL,     6, "Array overflow.")
DEF_ERROR (ERRVAL,      7, "Wrong input value.")
DEF_ERROR (ERRFEWARG,   8, "Too few arguments to do any arithmetic operation.")
